### ISSUE TITLE
Errors with 10.11 El Capitan

### ISSUE THREAD

**Issue by anumat** [orcudy/UCLALibrary#10]
I believe Swift's syntax has been updated, and we need to appropriate the changes in the application too. It could also be that the errors are because of beta software, and will be resolved by the time of the final release (of OS X).

The errors are of the form:

* "/Users/Anumat/Developer/UCLALibrary/Code/UCLALibrary/LibraryDisplayViewController.swift:138:51: Type of expression is ambiguous without more context"
* "/Users/Anumat/Developer/UCLALibrary/Code/UCLALibrary/LibraryDisplayViewController.swift:38:25: Cannot invoke initializer for type 'MKPlacemark' with an argument list of type '(coordinate: CLLocationCoordinate2D, addressDictionary: [NSObject : String])'"
* "/Users/Anumat/Developer/UCLALibrary/Code/UCLALibrary/AppDelegate.swift:120:44: Cannot convert value of type 'inout NSError?' (aka 'inout Optional<NSError>') to expected argument type '()'"

And a few others.

**Comment by orcudy** [comment]
Should be fixed now! Close this issue if the errors are gone. If not, screenshot the new errors and comment. =]
