### ISSUE TITLE
Ensure webservices API is returning correct library hours

### ISSUE THREAD

**Issue by orcudy** [orcudy/UCLALibrary#11]
Ensure that webservices hours response is consistent with the actual library hours.

Get library IDs from this URL:
http://webservices.library.ucla.edu/libservices/units

Then get the hours for a library by appending the ID onto this URL:
http://webservices.library.ucla.edu/libservices/hours/unit/

For instance, to get hours for Powell library (a.k.a. college library) use the following: 
http://webservices.library.ucla.edu/libservices/hours/unit/7

Compare the library hours with those listed here:
https://www.library.ucla.edu/hours

**Comment by anumat** [comment]
http://anumat.com/hours

The data returned by this API is in sync with the hours listed at https://www.library.ucla.edu/hours

Let me know if you'd like individual library hours by id.

**Comment by anumat** [comment]
Library hours by id also working correctly. For example:

http://anumat.com/hours/16
