### ISSUE TITLE
find and size photos for all supported libraries

### ISSUE THREAD

**Issue by orcudy** [orcudy/UCLALibrary#5]
gather photos from all available sources (talk to Chris and Doug about where to search for photos) save them in one central place, then resize photos (talk to Chris about sizing) in @1x @2x and @3x sizes

**Comment by dmcwo** [comment]
Hey @orcudy - here's our collection of photos (and a couple of floorplans, too):
https://ucla.box.com/s/dopzgaf7piajgd4l2vi8ibj8291qwd5m

**Comment by orcudy** [comment]
Completed
